FizzBuzzApplication.Web/Models/FizzBuzzModel.cs
namespace FizzBuzzApplication.Web.Models
{
    using System.ComponentModel.DataAnnotations;
    using FizzBuzzApplication.Web.Helper;
    using PagedList;

    public class FizzBuzzModel
    {
        [Required(ErrorMessage = FizzBuzzWebConstants.RequiredErrorMessage)]
        [Display(Name = FizzBuzzWebConstants.DisplayMessage)]
        [Range(FizzBuzzWebConstants.LowerLimit, FizzBuzzWebConstants.UpperLimit, ErrorMessage = FizzBuzzWebConstants.RangeErrorMessage)]
        public int Input { get; set; }

        public IPagedList<string> FizzBuzzList { get; set; }
    }
}

FizzBuzzApplication.Web/Controllers/FizzBuzzController.cs
namespace FizzBuzzApplication.Web.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using FizzBuzzApplication.Service.Interface;
    using FizzBuzzApplication.Web.Helper;
    using FizzBuzzApplication.Web.Models;
    using PagedList;

    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzService fizzBuzzService;

        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            this.fizzBuzzService = fizzBuzzService;
        }

        public ActionResult Display()
        {
            return this.View("Display");
        }

        [HttpPost]
        public ActionResult DisplayList(FizzBuzzModel fizzbuzz)
        {
            if (ModelState.IsValid)
            {
                fizzbuzz.FizzBuzzList = this.GetFizzBuzzList(fizzbuzz.Input).ToPagedList(1, FizzBuzzWebConstants.PageSize);
            }

            return View("Display", fizzbuzz);
        }

        [HttpGet]
        public ActionResult GetPagedList(FizzBuzzModel fizzbuzz, int page)
        {
            var model = new FizzBuzzModel() { Input = fizzbuzz.Input };
            model.FizzBuzzList = this.GetFizzBuzzList(fizzbuzz.Input).ToPagedList(page, FizzBuzzWebConstants.PageSize); ;
            return this.View("Display", model);
        }

        private IEnumerable<string> GetFizzBuzzList(int number)
        {
            var resultList = this.fizzBuzzService.GetFizzBuzzList(number);
            return resultList;
        }
    }
}

FizzBuzzApplication.Web/Views/FizzBuzz/Display.cshtml
@using FizzBuzzApplication.Web.Helper
@using PagedList.Mvc
@model FizzBuzzApplication.Web.Models.FizzBuzzModel

@{
    ViewBag.Title = "Display";
}

@using (Html.BeginForm("DisplayList", "FizzBuzz", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Input, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Input, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Input, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @{
        if (Model != null)
        {
            @Html.PrintList(Model.FizzBuzzList)

            <div>
                Page @(Model.FizzBuzzList.PageCount < Model.FizzBuzzList.PageNumber ? 0 : Model.FizzBuzzList.PageNumber) of @Model.FizzBuzzList.PageCount
                @Html.PagedListPager(Model.FizzBuzzList, page => Url.Action("GetPagedList", new { Input = Model.Input, page }), PagedListRenderOptions.TwitterBootstrapPager)
            </div>
        }
    }
</div>

FizzBuzzApplication.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/FizzBuzz.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <div class="navbar-header">
                    <div class="navbar-brand">FizzBuzz Application</div>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>